/**
 * ExportService Unit Tests
 * Tests PDF and CSV export functionality with validation
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ExportService } from '../ExportService';
import type { AnalyticsSection, DateRange } from '@/utils/pdfExport';

// Mock dependencies
vi.mock('@/utils/logger', () => ({
  logger: {
    log: vi.fn(),
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
  },
}));

vi.mock('@/utils/pdfExport', () => ({
  exportAnalyticsToPDF: vi.fn().mockResolvedValue(undefined),
}));

vi.mock('@/utils/export/csvExport', () => ({
  exportToCSV: vi.fn().mockResolvedValue(undefined),
  exportWithMetadata: vi.fn().mockResolvedValue(undefined),
}));

describe('ExportService', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('exportToPDF', () => {
    it('should export analytics sections to PDF', async () => {
      const sections: AnalyticsSection[] = [
        {
          title: 'Revenue Analytics',
          metrics: [
            { label: 'Total Revenue', value: '$10,000' },
            { label: 'Transactions', value: '150' },
          ],
        },
      ];

      const dateRange: DateRange = {
        start: '2025-01-01',
        end: '2025-01-31',
      };

      const config = {
        filename: 'revenue-analytics.pdf',
        title: 'Revenue Report',
        dateRange,
      };

      await expect(
        ExportService.exportToPDF(sections, config)
      ).resolves.not.toThrow();
    });

    it('should throw error with empty sections', async () => {
      const config = {
        filename: 'empty.pdf',
      };

      await expect(
        ExportService.exportToPDF([], config)
      ).rejects.toThrow('No data to export');
    });
  });

  describe('exportToCSV', () => {
    it('should export data to CSV', async () => {
      const data = [
        { Name: 'John', Score: 95, Grade: 'A' },
        { Name: 'Jane', Score: 87, Grade: 'B' },
      ];

      const config = {
        filename: 'students.csv',
      };

      await expect(
        ExportService.exportToCSV(data, config)
      ).resolves.not.toThrow();
    });

    it('should throw error with empty data', async () => {
      const config = {
        filename: 'empty.csv',
      };

      await expect(
        ExportService.exportToCSV([], config)
      ).rejects.toThrow('No data to export');
    });

    it('should enforce 50,000 row limit', async () => {
      const largeData = Array.from({ length: 50001 }, (_, i) => ({
        id: i,
        value: `Item ${i}`,
      }));

      const config = {
        filename: 'large-dataset.csv',
      };

      await expect(
        ExportService.exportToCSV(largeData, config)
      ).rejects.toThrow('Data exceeds maximum export size');
    });

    it('should allow export up to 50,000 rows', async () => {
      const largeData = Array.from({ length: 50000 }, (_, i) => ({
        id: i,
        value: `Item ${i}`,
      }));

      const config = {
        filename: 'max-dataset.csv',
      };

      await expect(
        ExportService.exportToCSV(largeData, config)
      ).resolves.not.toThrow();
    });

    it('should include custom headers when provided', async () => {
      const data = [
        { name: 'John', score: 95 },
        { name: 'Jane', score: 87 },
      ];

      const config = {
        filename: 'students.csv',
        headers: ['Student Name', 'Test Score'],
      };

      await expect(
        ExportService.exportToCSV(data, config)
      ).resolves.not.toThrow();
    });

    it('should include metadata when provided', async () => {
      const data = [
        { name: 'John', score: 95 },
      ];

      const config = {
        filename: 'students.csv',
        metadata: {
          'Report Date': '2025-01-31',
          'Generated By': 'Admin',
          'Class': '10th Grade',
        },
      };

      await expect(
        ExportService.exportToCSV(data, config)
      ).resolves.not.toThrow();
    });
  });

  describe('validateExportSize', () => {
    it('should validate data size is within limits', () => {
      const data = Array.from({ length: 1000 }, (_, i) => ({ id: i }));

      const result = ExportService.validateExportSize(data);

      expect(result.valid).toBe(true);
      expect(result.count).toBe(1000);
      expect(result.message).toBeUndefined();
    });

    it('should reject data exceeding 50,000 rows', () => {
      const data = Array.from({ length: 50001 }, (_, i) => ({ id: i }));

      const result = ExportService.validateExportSize(data);

      expect(result.valid).toBe(false);
      expect(result.count).toBe(50001);
      expect(result.message).toContain('exceeds maximum');
    });

    it('should accept exactly 50,000 rows', () => {
      const data = Array.from({ length: 50000 }, (_, i) => ({ id: i }));

      const result = ExportService.validateExportSize(data);

      expect(result.valid).toBe(true);
      expect(result.count).toBe(50000);
    });
  });

  describe('generateFilename', () => {
    it('should generate filename with timestamp', () => {
      const filename = ExportService.generateFilename('analytics', 'pdf');

      expect(filename).toMatch(/^analytics-\d{8}-\d{6}\.pdf$/);
    });

    it('should handle different file extensions', () => {
      const pdfFilename = ExportService.generateFilename('report', 'pdf');
      const csvFilename = ExportService.generateFilename('data', 'csv');

      expect(pdfFilename).toMatch(/\.pdf$/);
      expect(csvFilename).toMatch(/\.csv$/);
    });

    it('should sanitize section names', () => {
      const filename = ExportService.generateFilename('Revenue & Analytics', 'pdf');

      expect(filename).not.toContain('&');
      expect(filename).not.toContain(' ');
    });
  });
});
