-- Insert comprehensive course data for all audiences

-- Young Learners (Ages 8-11) - Additional courses
INSERT INTO courses (title, description, audience, mode, duration, price, level, start_date, features, category, keywords, prerequisites) VALUES
('AI Art Creator', 'Create amazing artwork using AI tools and learn about digital creativity', 'Young Learners', 'Online', '6 weeks', '₹3,999', 'Beginner', '15 Feb 2025', ARRAY['Digital Art', 'AI Tools', 'Creative Projects', 'Portfolio Building'], 'Creative AI', ARRAY['art', 'creativity', 'digital', 'beginner'], 'Basic computer skills'),
('Voice Assistant Builder', 'Build your own simple voice assistant and learn about speech recognition', 'Young Learners', 'Online', '4 weeks', '₹2,999', 'Beginner', '1 Mar 2025', ARRAY['Voice Recognition', 'Simple Coding', 'Interactive Projects', 'Speech Technology'], 'AI Applications', ARRAY['voice', 'assistant', 'speech', 'coding'], 'None'),
('AI Game Designer', 'Design simple games with AI characters and learn game development basics', 'Young Learners', 'Online', '8 weeks', '₹4,999', 'Beginner', '15 Mar 2025', ARRAY['Game Design', 'AI Characters', 'Storytelling', 'Interactive Media'], 'Gaming & AI', ARRAY['games', 'design', 'characters', 'fun'], 'Basic computer skills'),
('Smart Pet Trainer', 'Learn how AI helps train virtual pets and understand animal behavior', 'Young Learners', 'Online', '3 weeks', '₹1,999', 'Beginner', '1 Apr 2025', ARRAY['Virtual Pets', 'Behavior Learning', 'Care Systems', 'AI Training'], 'Fun with AI', ARRAY['pets', 'animals', 'care', 'virtual'], 'None'),
('AI Weather Wizard', 'Predict weather patterns using AI and create your own weather app', 'Young Learners', 'Online', '5 weeks', '₹3,499', 'Beginner', '15 Apr 2025', ARRAY['Weather Prediction', 'Data Patterns', 'Simple Apps', 'Science Fun'], 'Science & AI', ARRAY['weather', 'prediction', 'science', 'patterns'], 'Basic math skills');

-- Teenagers (Ages 12-18) - Additional courses  
INSERT INTO courses (title, description, audience, mode, duration, price, level, start_date, features, category, keywords, prerequisites) VALUES
('AI for Social Media', 'Master AI tools for content creation, analytics, and social media growth', 'Teenagers', 'Online', '6 weeks', '₹5,999', 'Intermediate', '1 Feb 2025', ARRAY['Content Creation', 'Analytics', 'Growth Hacking', 'AI Tools'], 'Digital Marketing', ARRAY['social media', 'content', 'marketing', 'analytics'], 'Basic social media knowledge'),
('Computer Vision Projects', 'Build image recognition apps and explore how AI sees the world', 'Teenagers', 'Online', '8 weeks', '₹7,999', 'Intermediate', '15 Feb 2025', ARRAY['Image Recognition', 'OpenCV', 'Python Programming', 'Real Projects'], 'Computer Vision', ARRAY['vision', 'images', 'recognition', 'opencv'], 'Basic Python knowledge'),
('AI Music Producer', 'Create music using AI tools and learn about algorithmic composition', 'Teenagers', 'Online', '7 weeks', '₹6,999', 'Intermediate', '1 Mar 2025', ARRAY['Music Generation', 'Audio Processing', 'Creative AI', 'Music Theory'], 'Creative AI', ARRAY['music', 'audio', 'composition', 'creative'], 'Interest in music'),
('Chatbot Developer Pro', 'Build advanced chatbots with natural language processing capabilities', 'Teenagers', 'Online', '10 weeks', '₹9,999', 'Advanced', '15 Mar 2025', ARRAY['NLP', 'Chatbot Development', 'API Integration', 'Advanced Programming'], 'Conversational AI', ARRAY['chatbot', 'nlp', 'conversation', 'development'], 'Programming experience'),
('AI for Gaming', 'Develop AI opponents and game mechanics using machine learning', 'Teenagers', 'Online', '12 weeks', '₹11,999', 'Advanced', '1 Apr 2025', ARRAY['Game AI', 'Machine Learning', 'Unity Integration', 'Advanced Projects'], 'Gaming & AI', ARRAY['gaming', 'ai opponents', 'unity', 'ml'], 'Programming and game design basics'),
('Data Science Explorer', 'Explore data science fundamentals and build predictive models', 'Teenagers', 'Online', '9 weeks', '₹8,999', 'Intermediate', '15 Apr 2025', ARRAY['Data Analysis', 'Predictive Models', 'Python', 'Statistics'], 'Data Science', ARRAY['data', 'science', 'analysis', 'prediction'], 'Basic math and statistics'),
('AI Ethics & Society', 'Understand AI impact on society and develop ethical AI practices', 'Teenagers', 'Online', '4 weeks', '₹3,999', 'Beginner', '1 May 2025', ARRAY['Ethics Discussion', 'Social Impact', 'Case Studies', 'Critical Thinking'], 'AI Ethics', ARRAY['ethics', 'society', 'impact', 'responsibility'], 'None'),
('Robotics & AI', 'Combine robotics with AI to build intelligent autonomous systems', 'Teenagers', 'Hybrid', '14 weeks', '₹15,999', 'Advanced', '15 May 2025', ARRAY['Robotics Hardware', 'AI Programming', 'Sensors', 'Automation'], 'Robotics', ARRAY['robotics', 'automation', 'sensors', 'hardware'], 'Programming and electronics basics');

-- Professionals - Additional courses
INSERT INTO courses (title, description, audience, mode, duration, price, level, start_date, features, category, keywords, prerequisites) VALUES
('AI Project Management', 'Master AI implementation strategies and project management methodologies', 'Professionals', 'Online', '6 weeks', '₹12,999', 'Intermediate', '1 Feb 2025', ARRAY['Project Planning', 'AI Strategy', 'Team Management', 'ROI Analysis'], 'Management', ARRAY['project management', 'strategy', 'implementation', 'roi'], 'Management experience'),
('Machine Learning for Finance', 'Apply ML techniques to financial analysis, risk assessment, and trading', 'Professionals', 'Online', '10 weeks', '₹18,999', 'Advanced', '15 Feb 2025', ARRAY['Financial Models', 'Risk Analysis', 'Algorithmic Trading', 'Regulatory Compliance'], 'Finance & AI', ARRAY['finance', 'trading', 'risk', 'algorithms'], 'Finance background'),
('AI in Healthcare', 'Implement AI solutions for medical diagnosis, treatment, and patient care', 'Professionals', 'Online', '8 weeks', '₹16,999', 'Advanced', '1 Mar 2025', ARRAY['Medical AI', 'Diagnostic Tools', 'Patient Data', 'Healthcare Compliance'], 'Healthcare AI', ARRAY['healthcare', 'medical', 'diagnosis', 'patient care'], 'Healthcare background'),
('Natural Language Processing', 'Build advanced NLP applications for text analysis and understanding', 'Professionals', 'Online', '12 weeks', '₹22,999', 'Advanced', '15 Mar 2025', ARRAY['Text Processing', 'Language Models', 'Sentiment Analysis', 'API Development'], 'NLP', ARRAY['nlp', 'text analysis', 'language', 'processing'], 'Programming experience'),
('AI Sales & Marketing', 'Leverage AI for customer insights, lead generation, and sales optimization', 'Professionals', 'Online', '7 weeks', '₹14,999', 'Intermediate', '1 Apr 2025', ARRAY['Customer Analytics', 'Lead Scoring', 'Personalization', 'Sales Automation'], 'Sales & Marketing', ARRAY['sales', 'marketing', 'customer', 'automation'], 'Sales or marketing experience'),
('Computer Vision for Industry', 'Implement computer vision solutions for manufacturing and quality control', 'Professionals', 'Online', '9 weeks', '₹19,999', 'Advanced', '15 Apr 2025', ARRAY['Industrial Vision', 'Quality Control', 'Defect Detection', 'Process Automation'], 'Industrial AI', ARRAY['computer vision', 'manufacturing', 'quality', 'industrial'], 'Technical background'),
('AI Product Development', 'Design and develop AI-powered products from concept to market', 'Professionals', 'Online', '11 weeks', '₹24,999', 'Advanced', '1 May 2025', ARRAY['Product Strategy', 'AI Integration', 'User Experience', 'Market Analysis'], 'Product Management', ARRAY['product development', 'ai products', 'strategy', 'market'], 'Product development experience'),
('Deep Learning Specialist', 'Master deep neural networks and advanced AI architectures', 'Professionals', 'Online', '16 weeks', '₹29,999', 'Expert', '15 May 2025', ARRAY['Neural Networks', 'Deep Learning', 'TensorFlow', 'PyTorch'], 'Deep Learning', ARRAY['deep learning', 'neural networks', 'tensorflow', 'pytorch'], 'Strong programming and ML background'),
('AI Consulting Skills', 'Develop expertise in AI consulting and client solution delivery', 'Professionals', 'Online', '8 weeks', '₹17,999', 'Intermediate', '1 Jun 2025', ARRAY['Consulting Framework', 'Client Management', 'Solution Design', 'Presentation Skills'], 'Consulting', ARRAY['consulting', 'client management', 'solutions', 'advisory'], 'Professional experience'),
('Automated Testing with AI', 'Implement AI-driven testing strategies and quality assurance', 'Professionals', 'Online', '6 weeks', '₹13,999', 'Intermediate', '15 Jun 2025', ARRAY['Test Automation', 'AI Testing', 'Quality Assurance', 'Test Optimization'], 'Software Testing', ARRAY['testing', 'automation', 'quality', 'software'], 'Software testing experience');

-- SMEs (Small & Medium Enterprises) - New courses
INSERT INTO courses (title, description, audience, mode, duration, price, level, start_date, features, category, keywords, prerequisites) VALUES
('AI Strategy for SMEs', 'Develop comprehensive AI adoption strategies for small and medium enterprises', 'SMEs', 'Online', '4 weeks', '₹15,999', 'Executive', '1 Feb 2025', ARRAY['Strategic Planning', 'AI Roadmap', 'Budget Planning', 'Risk Assessment'], 'Strategy', ARRAY['strategy', 'planning', 'roadmap', 'adoption'], 'Business leadership experience'),
('Customer Service AI', 'Implement AI-powered customer service solutions to improve satisfaction', 'SMEs', 'Hybrid', '6 weeks', '₹19,999', 'Intermediate', '15 Feb 2025', ARRAY['Chatbot Implementation', 'Service Automation', 'Customer Analytics', 'Support Optimization'], 'Customer Service', ARRAY['customer service', 'automation', 'support', 'satisfaction'], 'Customer service management'),
('AI-Powered Inventory Management', 'Optimize inventory with AI forecasting and automated ordering systems', 'SMEs', 'Online', '5 weeks', '₹17,999', 'Intermediate', '1 Mar 2025', ARRAY['Inventory Forecasting', 'Demand Prediction', 'Supply Chain AI', 'Cost Optimization'], 'Operations', ARRAY['inventory', 'forecasting', 'supply chain', 'optimization'], 'Operations management'),
('Marketing Automation with AI', 'Scale marketing efforts using AI tools for personalization and automation', 'SMEs', 'Online', '7 weeks', '₹21,999', 'Intermediate', '15 Mar 2025', ARRAY['Marketing Automation', 'Personalization', 'Lead Nurturing', 'Campaign Optimization'], 'Marketing', ARRAY['marketing', 'automation', 'personalization', 'campaigns'], 'Marketing experience'),
('Financial Analytics & AI', 'Leverage AI for financial planning, analysis, and business intelligence', 'SMEs', 'Online', '6 weeks', '₹18,999', 'Advanced', '1 Apr 2025', ARRAY['Financial Modeling', 'Predictive Analytics', 'Cash Flow Forecasting', 'Business Intelligence'], 'Finance', ARRAY['finance', 'analytics', 'forecasting', 'intelligence'], 'Financial management background'),
('HR & Talent Management AI', 'Transform recruitment and employee management with AI solutions', 'SMEs', 'Online', '5 weeks', '₹16,999', 'Intermediate', '15 Apr 2025', ARRAY['Recruitment Automation', 'Employee Analytics', 'Performance Prediction', 'Talent Retention'], 'Human Resources', ARRAY['hr', 'recruitment', 'talent', 'analytics'], 'HR management experience'),
('E-commerce AI Solutions', 'Implement AI for product recommendations, pricing, and customer experience', 'SMEs', 'Online', '8 weeks', '₹23,999', 'Advanced', '1 May 2025', ARRAY['Recommendation Systems', 'Dynamic Pricing', 'Customer Segmentation', 'Conversion Optimization'], 'E-commerce', ARRAY['ecommerce', 'recommendations', 'pricing', 'optimization'], 'E-commerce experience'),
('Manufacturing Process AI', 'Optimize manufacturing operations with AI-driven process improvements', 'SMEs', 'Hybrid', '10 weeks', '₹29,999', 'Advanced', '15 May 2025', ARRAY['Process Optimization', 'Predictive Maintenance', 'Quality Control', 'Production Planning'], 'Manufacturing', ARRAY['manufacturing', 'optimization', 'maintenance', 'quality'], 'Manufacturing background'),
('Data-Driven Decision Making', 'Build data analytics capabilities for informed business decisions', 'SMEs', 'Online', '6 weeks', '₹19,999', 'Intermediate', '1 Jun 2025', ARRAY['Business Analytics', 'Data Visualization', 'KPI Tracking', 'Decision Frameworks'], 'Analytics', ARRAY['analytics', 'data', 'decisions', 'visualization'], 'Business management'),
('AI Team Training Program', 'Comprehensive AI literacy program for entire business teams', 'SMEs', 'Hybrid', '12 weeks', '₹35,999', 'Beginner', '15 Jun 2025', ARRAY['Team Training', 'AI Literacy', 'Hands-on Workshops', 'Implementation Support'], 'Team Development', ARRAY['team training', 'literacy', 'workshops', 'implementation'], 'None'),
('Competitive Intelligence AI', 'Use AI for market research and competitive analysis', 'SMEs', 'Online', '4 weeks', '₹14,999', 'Intermediate', '1 Jul 2025', ARRAY['Market Research', 'Competitor Analysis', 'Trend Prediction', 'Intelligence Gathering'], 'Business Intelligence', ARRAY['intelligence', 'research', 'competition', 'analysis'], 'Business development experience'),
('AI Risk Management', 'Identify and mitigate AI implementation risks in business operations', 'SMEs', 'Online', '5 weeks', '₹17,999', 'Advanced', '15 Jul 2025', ARRAY['Risk Assessment', 'Compliance Management', 'Security Protocols', 'Mitigation Strategies'], 'Risk Management', ARRAY['risk', 'compliance', 'security', 'management'], 'Risk management background'),
('Digital Transformation with AI', 'Lead complete digital transformation initiatives powered by AI', 'SMEs', 'Hybrid', '14 weeks', '₹39,999', 'Executive', '1 Aug 2025', ARRAY['Digital Strategy', 'Transformation Planning', 'Change Management', 'Technology Integration'], 'Digital Transformation', ARRAY['digital transformation', 'strategy', 'change', 'integration'], 'Senior leadership experience'),
('AI ROI Measurement', 'Measure and optimize return on investment for AI implementations', 'SMEs', 'Online', '3 weeks', '₹12,999', 'Advanced', '15 Aug 2025', ARRAY['ROI Calculation', 'Performance Metrics', 'Cost-Benefit Analysis', 'Value Measurement'], 'Performance Management', ARRAY['roi', 'measurement', 'metrics', 'performance'], 'Financial analysis background'),
('Supply Chain AI Optimization', 'Revolutionize supply chain management with AI-driven solutions', 'SMEs', 'Online', '9 weeks', '₹26,999', 'Advanced', '1 Sep 2025', ARRAY['Supply Chain Analytics', 'Logistics Optimization', 'Vendor Management', 'Demand Planning'], 'Supply Chain', ARRAY['supply chain', 'logistics', 'vendor', 'planning'], 'Supply chain management'),
('AI for Sustainability', 'Implement AI solutions for environmental sustainability and ESG goals', 'SMEs', 'Online', '6 weeks', '₹20,999', 'Intermediate', '15 Sep 2025', ARRAY['Sustainability Analytics', 'Environmental Impact', 'ESG Reporting', 'Green Technology'], 'Sustainability', ARRAY['sustainability', 'environment', 'esg', 'green'], 'Sustainability knowledge'),
('Custom AI Development', 'Build bespoke AI solutions tailored to specific business needs', 'SMEs', 'Custom', '16 weeks', 'Enquire for pricing', 'Expert', 'Enquire for start date', ARRAY['Custom Development', 'Business-Specific Solutions', 'Dedicated Support', 'Implementation Assistance'], 'Custom Solutions', ARRAY['custom', 'bespoke', 'tailored', 'development'], 'Technical requirements discussion'),
('AI Governance & Ethics', 'Establish AI governance frameworks and ethical guidelines for business', 'SMEs', 'Online', '4 weeks', '₹16,999', 'Executive', '1 Oct 2025', ARRAY['Governance Framework', 'Ethical Guidelines', 'Policy Development', 'Compliance Standards'], 'Governance', ARRAY['governance', 'ethics', 'policy', 'compliance'], 'Leadership experience'),
('AI Vendor Selection', 'Navigate AI vendor landscape and make informed technology choices', 'SMEs', 'Online', '3 weeks', '₹13,999', 'Intermediate', '15 Oct 2025', ARRAY['Vendor Evaluation', 'Technology Assessment', 'Contract Negotiation', 'Implementation Planning'], 'Vendor Management', ARRAY['vendor', 'selection', 'evaluation', 'technology'], 'Procurement experience'),
('Scaling AI Operations', 'Scale AI implementations across multiple business units and functions', 'SMEs', 'Hybrid', '11 weeks', '₹31,999', 'Advanced', '1 Nov 2025', ARRAY['Scaling Strategies', 'Cross-Functional Implementation', 'Operations Management', 'Performance Monitoring'], 'Operations Scaling', ARRAY['scaling', 'operations', 'implementation', 'monitoring'], 'Operations leadership');