-- Migration: Create Event Series Registrations Table
-- Description: Tracks user registration for entire recurring event series
-- Created: 2025-11-06

CREATE TABLE IF NOT EXISTS public.event_series_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_id INTEGER NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  registered_at TIMESTAMPTZ DEFAULT now(),
  payment_status VARCHAR(20) DEFAULT 'completed' CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
  payment_amount DECIMAL(10,2) DEFAULT 0.00,
  payment_method VARCHAR(50),
  auto_generate_tickets BOOLEAN DEFAULT true,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, event_id)
);

-- Indexes
CREATE INDEX idx_event_series_registrations_user_id ON public.event_series_registrations(user_id);
CREATE INDEX idx_event_series_registrations_event_id ON public.event_series_registrations(event_id);
CREATE INDEX idx_event_series_registrations_payment_status ON public.event_series_registrations(payment_status);

-- Enable RLS
ALTER TABLE public.event_series_registrations ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- Users can view their own registrations
CREATE POLICY "Users can view own event series registrations"
  ON public.event_series_registrations
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- Users can insert their own registrations
CREATE POLICY "Users can create own event series registrations"
  ON public.event_series_registrations
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Users can update their own registrations
CREATE POLICY "Users can update own event series registrations"
  ON public.event_series_registrations
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Admins can view all registrations
CREATE POLICY "Admins can view all event series registrations"
  ON public.event_series_registrations
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- Admins can manage all registrations
CREATE POLICY "Admins can manage all event series registrations"
  ON public.event_series_registrations
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_event_series_registrations_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER event_series_registrations_updated_at
  BEFORE UPDATE ON public.event_series_registrations
  FOR EACH ROW
  EXECUTE FUNCTION update_event_series_registrations_updated_at();

-- Function to auto-generate tickets for all future sessions when user registers for series
CREATE OR REPLACE FUNCTION auto_generate_event_session_tickets()
RETURNS TRIGGER AS $$
DECLARE
  session_record RECORD;
  qr_data TEXT;
BEGIN
  -- Only proceed if auto_generate_tickets is true
  IF NEW.auto_generate_tickets = true THEN
    -- Generate tickets for all future scheduled sessions
    FOR session_record IN
      SELECT id, event_id
      FROM public.event_sessions
      WHERE event_id = NEW.event_id
      AND status IN ('scheduled', 'draft')
      AND session_date >= CURRENT_DATE
    LOOP
      -- Generate QR code data
      qr_data := 'QR:EVT:' || NEW.user_id || ':' || session_record.id || ':' || gen_random_uuid() || ':' || EXTRACT(EPOCH FROM now())::TEXT;

      -- Insert ticket (ticket_number will be auto-generated by trigger)
      INSERT INTO public.event_session_tickets (
        user_id,
        event_id,
        session_id,
        status,
        qr_code
      )
      VALUES (
        NEW.user_id,
        NEW.event_id,
        session_record.id,
        'active',
        qr_data
      )
      ON CONFLICT (user_id, session_id) DO NOTHING;  -- Prevent duplicates
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER auto_generate_event_tickets_on_registration
  AFTER INSERT ON public.event_series_registrations
  FOR EACH ROW
  EXECUTE FUNCTION auto_generate_event_session_tickets();

-- Function to generate tickets for new sessions added to a series
CREATE OR REPLACE FUNCTION auto_generate_tickets_for_new_session()
RETURNS TRIGGER AS $$
DECLARE
  reg_record RECORD;
  qr_data TEXT;
BEGIN
  -- Only for future scheduled sessions
  IF NEW.session_date >= CURRENT_DATE AND NEW.status IN ('scheduled', 'draft') THEN
    -- Generate tickets for all users registered for this event series
    FOR reg_record IN
      SELECT user_id, event_id
      FROM public.event_series_registrations
      WHERE event_id = NEW.event_id
      AND auto_generate_tickets = true
      AND payment_status = 'completed'
    LOOP
      -- Generate QR code data
      qr_data := 'QR:EVT:' || reg_record.user_id || ':' || NEW.id || ':' || gen_random_uuid() || ':' || EXTRACT(EPOCH FROM now())::TEXT;

      -- Insert ticket
      INSERT INTO public.event_session_tickets (
        user_id,
        event_id,
        session_id,
        status,
        qr_code
      )
      VALUES (
        reg_record.user_id,
        reg_record.event_id,
        NEW.id,
        'active',
        qr_data
      )
      ON CONFLICT (user_id, session_id) DO NOTHING;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER auto_generate_tickets_for_new_event_session
  AFTER INSERT ON public.event_sessions
  FOR EACH ROW
  EXECUTE FUNCTION auto_generate_tickets_for_new_session();

-- Comments
COMMENT ON TABLE public.event_series_registrations IS 'User registrations for recurring event series';
COMMENT ON COLUMN public.event_series_registrations.auto_generate_tickets IS 'Automatically create tickets for all future sessions when true';
COMMENT ON COLUMN public.event_series_registrations.payment_status IS 'Free events use completed with amount 0.00';
