// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables are required for Supabase configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      'x-application-name': 'aiborg-learn-sphere',
    },
  },
});

// Enhanced realtime authentication helper
// This ensures WebSocket connections include the user's access token
let _realtimeAccessToken: string | null = null;

// Update access token when auth state changes
supabase.auth.onAuthStateChange((event, session) => {
  if (session?.access_token) {
    _realtimeAccessToken = session.access_token;
    // Update realtime connection with new token
    if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
      supabase.realtime.setAuth(session.access_token);
    }
  } else if (event === 'SIGNED_OUT') {
    realtimeAccessToken = null;
    supabase.realtime.setAuth(null);
  }
});

// Initialize token from existing session
(async () => {
  const {
    data: { session },
  } = await supabase.auth.getSession();
  if (session?.access_token) {
    realtimeAccessToken = session.access_token;
    supabase.realtime.setAuth(session.access_token);
  }
})();
